version: '3'
services:
  back-end-service:
    image: backend:1.0
    ports:
      - "5000:5000"
    environment:
      - CURRENT_ENVIRONMENT=development
    volumes:
      - back-end-data:/app/logs  # Mount a named volume to persist data

  front-end-service:
    image: frontend:1.0
    ports:
      - "8080:8080"
    environment:
      - CURRENT_ENVIRONMENT=development

volumes:
  back-end-data:
